// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbqI8kUhgf7eaW-pAanr-LlQunz-v3WzE',
    appId: '1:294379047311:web:7ca62d1b7cc2b95c31e3fa',
    messagingSenderId: '294379047311',
    projectId: 'tifl-tailes',
    authDomain: 'tifl-tailes.firebaseapp.com',
    storageBucket: 'tifl-tailes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllvvlrMc7kIcC-7ZyXlq5uGA8blv8GGs',
    appId: '1:294379047311:android:0d8c865f4c7e31db31e3fa',
    messagingSenderId: '294379047311',
    projectId: 'tifl-tailes',
    storageBucket: 'tifl-tailes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeypSrW1itnkZXfbM3zBhfQ-826FbELa0',
    appId: '1:294379047311:ios:82253b6b832ce7b431e3fa',
    messagingSenderId: '294379047311',
    projectId: 'tifl-tailes',
    storageBucket: 'tifl-tailes.firebasestorage.app',
    iosBundleId: 'com.tifltailes.com',
  );
}
